//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public int car_id { get; set; }
        public string car_name { get; set; }
        public Nullable<int> car_price { get; set; }
        public Nullable<int> customer_id { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
